### ISSUE TITLE
@@ 페이지 옆으로 넘기는 기능

### ISSUE THREAD

**Issue by Cutiepazzipozzi** [Cutiepazzipozzi/JPA_practice_small#7]

**Comment by kyw0716** [comment]
html 파일

<div id="bannerWrapper">
  <div id="imageContainer">
    <div id="item1">1</div>
    <div id="item2">2</div>
    <div id="item3">3</div>
  </div>
  <div id="leftBtn"><</div>
  <div id="rightBtn">></div>
</div>

**Comment by Cutiepazzipozzi** [comment]
영우가 해결해쥼... js 연결하여 완료!!!!
